"""
Agent Framework — Phase 7

=== THEORY ===

This framework implements the Actor model combined with the ReAct
(Reasoning + Acting) pattern introduced by Yao et al. (2023).

The key insight of ReAct:
  LLMs interleave Thought → Action → Observation loops.
  Each iteration refines the agent's understanding before acting.

Our agents are DETERMINISTIC actors (no LLM reasoning loop) — they
encapsulate a specialist skill (planning, retrieval, critique, synthesis)
and execute it as a reusable, composable unit.

=== ARCHITECTURE ===

  AgentTask
    │  (input: goal, params, priority)
    ▼
  AgentLifecycle
    │  PENDING → RUNNING → DONE | FAILED | TIMED_OUT | CANCELLED
    ▼
  Agent.run(task, context)
    │  reads AgentContext (shared retrieval, memory, tools)
    │  writes to AgentMemory (per-agent state)
    ▼
  AgentResult
       (output, evidence, metadata, latency)

=== DATA STRUCTURES ===

  AgentTask    — input unit; immutable after creation
  AgentResult  — output unit; final state of one execution
  AgentContext — shared environment (retriever, DB, tools)
  AgentMemory  — per-agent mutable state across runs
  AgentLifecycle — state machine for one task execution

=== COMPLEXITY ===

  Agent.run():  depends on agent type; framework overhead is O(1)
  AgentMemory.append(): amortised O(1) (list append + bounded trim)
  RetryPolicy.should_retry(): O(1)

=== SPACE COMPLEXITY ===

  AgentMemory: O(max_entries) per agent
  AgentResult: O(len(evidence)) — bounded by retrieval top_k

=== TRADEOFFS ===

  + Fully synchronous for simplicity (no asyncio overhead)
  + Retries with exponential backoff (configurable)
  + Timeout enforcement via time.perf_counter()
  + All state is dataclass-based (no mutable globals)
  - No distributed coordination (single-process only)
  - No LLM reasoning loop (rule-based, fast, predictable)

=== PRODUCTION EQUIVALENTS ===

  CrewAI:   Agent class with role/goal/backstory + Task
  LangGraph: StateGraph nodes + edges
  AutoGen:  ConversableAgent with reply function
  OpenAI:   Assistant API with function tools

"""

import logging
import time
import uuid
from abc import ABC, abstractmethod
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

logger = logging.getLogger(__name__)


# ── Enumerations ──────────────────────────────────────────────────────────────

class AgentStatus(str, Enum):
    PENDING    = "pending"
    RUNNING    = "running"
    DONE       = "done"
    FAILED     = "failed"
    TIMED_OUT  = "timed_out"
    CANCELLED  = "cancelled"


class AgentType(str, Enum):
    PLANNER           = "planner"
    RETRIEVAL         = "retrieval"
    CRITIC            = "critic"
    CITATION_VALIDATOR = "citation_validator"
    SYNTHESIS         = "synthesis"


class TaskPriority(int, Enum):
    LOW    = 1
    NORMAL = 5
    HIGH   = 10
    URGENT = 20


# ── Task ─────────────────────────────────────────────────────────────────────

@dataclass
class AgentTask:
    """
    The unit of work dispatched to an agent.

    Immutable after creation — modifying a task in-flight leads to
    race conditions in parallel execution graphs.

    Fields:
      task_id      — unique identifier (auto-generated UUID)
      task_type    — human-readable label (e.g. "retrieve", "plan")
      goal         — natural-language description of what to accomplish
      params       — arbitrary key-value inputs for the agent
      priority     — scheduling weight (higher = run first)
      timeout_sec  — wall-clock limit; 0 = unlimited
      parent_id    — for sub-tasks generated by the planner
      depends_on   — list of task_ids this task must wait for
    """
    goal:       str
    task_type:  str                   = "generic"
    params:     dict[str, Any]        = field(default_factory=dict)
    priority:   TaskPriority          = TaskPriority.NORMAL
    timeout_sec: float                = 60.0
    parent_id:  Optional[str]         = None
    depends_on: list[str]             = field(default_factory=list)
    task_id:    str                   = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: float                 = field(default_factory=time.time)


# ── Result ────────────────────────────────────────────────────────────────────

@dataclass
class AgentResult:
    """
    Final output of one agent execution.

    Fields:
      task_id      — echoes the input task
      agent_type   — which agent produced this
      status       — terminal state
      output       — primary result (string, dict, or list)
      evidence     — list of supporting facts/chunks gathered
      confidence   — agent's self-assessed confidence in [0, 1]
      metadata     — auxiliary data (tokens used, sources, etc.)
      error        — error message when status == FAILED
      latency_ms   — wall-clock time for this execution
      attempts     — how many tries (including retries)
    """
    task_id:    str
    agent_type: AgentType
    status:     AgentStatus
    output:     Any
    evidence:   list[dict]            = field(default_factory=list)
    confidence: float                 = 0.0
    metadata:   dict[str, Any]        = field(default_factory=dict)
    error:      Optional[str]         = None
    latency_ms: float                 = 0.0
    attempts:   int                   = 1

    def is_success(self) -> bool:
        return self.status == AgentStatus.DONE

    def to_dict(self) -> dict:
        return {
            "task_id":    self.task_id,
            "agent_type": self.agent_type.value,
            "status":     self.status.value,
            "output":     self.output,
            "confidence": round(self.confidence, 4),
            "latency_ms": round(self.latency_ms, 2),
            "attempts":   self.attempts,
            "error":      self.error,
        }


# ── Context ───────────────────────────────────────────────────────────────────

@dataclass
class AgentContext:
    """
    Shared environment injected into every agent.

    Holds references to all infrastructure components so individual
    agents don't need to know how to construct them.  This is the
    Dependency Injection container for the agent layer.

    Fields:
      retriever      — Phase 5 RetrievalPipeline or Phase 4 HybridSearchService
      db             — Database instance
      rag_pipeline   — Phase 6 RAGPipeline (for answer generation)
      memory         — Phase 6 MemoryService (conversation memory)
      tools          — dict[tool_name → Tool instance]
      config         — Phase 7 AgentConfig (retries, timeouts, etc.)
      session_id     — current research session identifier
      user_id        — optional user identifier
      event_bus      — Phase 8 EventBus (optional, for publishing events)
      redis          — Phase 8 RedisClient (optional, for distributed state)
      extra          — catch-all for phase-specific extras
    """
    retriever:    Any   = None
    db:           Any   = None
    rag_pipeline: Any   = None
    memory:       Any   = None
    tools:        dict  = field(default_factory=dict)
    config:       Any   = None
    session_id:   Optional[str] = None
    user_id:      Optional[str] = None
    event_bus:    Any   = None
    redis:        Any   = None
    extra:        dict[str, Any] = field(default_factory=dict)


# ── Memory ────────────────────────────────────────────────────────────────────

class AgentMemory:
    """
    Per-agent ephemeral memory for a single research session.

    Agents accumulate observations across task iterations, enabling
    them to avoid redundant work and build on prior results.

    Implementation: bounded deque (FIFO eviction) with O(1) append.

    Compared to LangChain ConversationBufferMemory:
      - No LLM-based compression
      - Simpler structure: list of dicts
      - Bounded size prevents unbounded growth
    """

    def __init__(self, max_entries: int = 100):
        self._entries: deque[dict] = deque(maxlen=max_entries)
        self._max = max_entries

    def remember(self, key: str, value: Any, metadata: dict | None = None) -> None:
        entry = {
            "key":       key,
            "value":     value,
            "metadata":  metadata or {},
            "timestamp": time.time(),
        }
        self._entries.append(entry)

    def recall(self, key: str) -> list[Any]:
        return [e["value"] for e in self._entries if e["key"] == key]

    def recall_latest(self, key: str) -> Optional[Any]:
        matches = self.recall(key)
        return matches[-1] if matches else None

    def all_entries(self) -> list[dict]:
        return list(self._entries)

    def clear(self) -> None:
        self._entries.clear()

    def __len__(self) -> int:
        return len(self._entries)


# ── Lifecycle ─────────────────────────────────────────────────────────────────

class AgentLifecycle:
    """
    State machine for one task execution.

    States:
      PENDING → RUNNING → DONE
                        → FAILED
                        → TIMED_OUT
                        → CANCELLED

    Transitions are enforced; illegal transitions raise RuntimeError.

    The lifecycle also tracks wall-clock time for latency reporting.
    """

    _VALID_TRANSITIONS: dict[AgentStatus, set[AgentStatus]] = {
        AgentStatus.PENDING:   {AgentStatus.RUNNING, AgentStatus.CANCELLED},
        AgentStatus.RUNNING:   {AgentStatus.DONE, AgentStatus.FAILED, AgentStatus.TIMED_OUT, AgentStatus.CANCELLED},
        AgentStatus.DONE:      set(),
        AgentStatus.FAILED:    set(),
        AgentStatus.TIMED_OUT: set(),
        AgentStatus.CANCELLED: set(),
    }

    def __init__(self) -> None:
        self._status  = AgentStatus.PENDING
        self._started: Optional[float] = None
        self._ended:   Optional[float] = None

    def transition(self, new_status: AgentStatus) -> None:
        allowed = self._VALID_TRANSITIONS.get(self._status, set())
        if new_status not in allowed:
            raise RuntimeError(
                f"Illegal lifecycle transition {self._status} → {new_status}"
            )
        if new_status == AgentStatus.RUNNING:
            self._started = time.perf_counter()
        elif new_status in (AgentStatus.DONE, AgentStatus.FAILED, AgentStatus.TIMED_OUT):
            self._ended = time.perf_counter()
        self._status = new_status

    @property
    def status(self) -> AgentStatus:
        return self._status

    @property
    def latency_ms(self) -> float:
        if self._started is None:
            return 0.0
        end = self._ended or time.perf_counter()
        return round((end - self._started) * 1000, 2)

    def is_terminal(self) -> bool:
        return self._status in (
            AgentStatus.DONE, AgentStatus.FAILED,
            AgentStatus.TIMED_OUT, AgentStatus.CANCELLED,
        )


# ── Retry Policy ──────────────────────────────────────────────────────────────

@dataclass
class RetryPolicy:
    """
    Exponential backoff retry policy.

    max_attempts:    total attempts including the first one
    base_delay_sec:  initial delay (doubles each retry)
    max_delay_sec:   cap on the delay
    """
    max_attempts:  int   = 3
    base_delay_sec: float = 0.5
    max_delay_sec:  float = 10.0

    def delay_for(self, attempt: int) -> float:
        """Return sleep duration in seconds for attempt N (0-indexed)."""
        if attempt == 0:
            return 0.0
        raw = self.base_delay_sec * (2 ** (attempt - 1))
        return min(raw, self.max_delay_sec)

    def should_retry(self, attempt: int) -> bool:
        return attempt < self.max_attempts


# ── Abstract Agent ─────────────────────────────────────────────────────────────

class Agent(ABC):
    """
    Base class for all Phase 7 agents.

    Subclasses implement `_execute()`.  The base class handles:
      - lifecycle state transitions
      - timeout enforcement
      - retry with exponential backoff
      - latency tracking
      - logging + error capture

    Usage:
        class MyAgent(Agent):
            @property
            def agent_type(self) -> AgentType:
                return AgentType.PLANNER

            def _execute(self, task, context, memory) -> AgentResult:
                ...

        agent = MyAgent(retry_policy=RetryPolicy(max_attempts=2))
        result = agent.run(task, context)
    """

    def __init__(
        self,
        retry_policy: RetryPolicy | None = None,
        memory: AgentMemory | None = None,
    ) -> None:
        self._retry  = retry_policy or RetryPolicy()
        self._memory = memory or AgentMemory()

    @property
    @abstractmethod
    def agent_type(self) -> AgentType:
        """Return the agent's type identifier."""

    @abstractmethod
    def _execute(
        self,
        task:    AgentTask,
        context: AgentContext,
        memory:  AgentMemory,
    ) -> AgentResult:
        """
        Core logic.  Must return an AgentResult.
        Should NOT raise exceptions — catch internally and return FAILED result.
        """

    def run(self, task: AgentTask, context: AgentContext) -> AgentResult:
        """
        Execute the task with lifecycle management, timeout, and retries.

        Returns a terminal AgentResult (status DONE or FAILED or TIMED_OUT).
        """
        lc = AgentLifecycle()
        lc.transition(AgentStatus.RUNNING)

        last_result: Optional[AgentResult] = None
        last_error:  Optional[str]         = None

        for attempt in range(self._retry.max_attempts):
            delay = self._retry.delay_for(attempt)
            if delay > 0:
                time.sleep(delay)

            try:
                deadline = time.perf_counter() + task.timeout_sec if task.timeout_sec > 0 else None
                result = self._execute(task, context, self._memory)

                # Enforce timeout at coarse granularity
                if deadline and time.perf_counter() > deadline:
                    last_error = f"Timeout after {task.timeout_sec}s"
                    logger.warning("%s task %s timed out", self.agent_type.value, task.task_id[:8])
                    continue

                last_result = result
                if result.status == AgentStatus.DONE:
                    break
                last_error = result.error

            except Exception as exc:
                last_error = str(exc)
                logger.exception("%s task %s attempt %d failed: %s",
                                 self.agent_type.value, task.task_id[:8], attempt + 1, exc)

        if last_result and last_result.status == AgentStatus.DONE:
            lc.transition(AgentStatus.DONE)
            last_result.latency_ms  = lc.latency_ms
            last_result.attempts    = attempt + 1
            return last_result

        # All attempts exhausted
        if last_error and "Timeout" in (last_error or ""):
            terminal = AgentStatus.TIMED_OUT
        else:
            terminal = AgentStatus.FAILED
        lc.transition(terminal)

        return AgentResult(
            task_id    = task.task_id,
            agent_type = self.agent_type,
            status     = terminal,
            output     = None,
            error      = last_error or "Unknown error",
            latency_ms = lc.latency_ms,
            attempts   = self._retry.max_attempts,
        )

    @property
    def memory(self) -> AgentMemory:
        return self._memory
